### ISSUE TITLE
Ревью по проекту

### ISSUE THREAD

**Issue by akhtyamovpavel** [DramatikMan/MLHL-02-EDA-project#7]
Привет! Посмотрел проект - в целом, всё круто! У меня есть только минорные замечания, и те - в скрапперах:

- [x] https://github.com/DramatikMan/MLHL-02-EDA-project/blob/main/app/runner.py#L29-L36 - мы не хотим вынести запрос в другое место, чтобы он не загружал место? Плюс ещё так (мне кажется) будет проще поменять wrapper после этого
- [x] https://github.com/DramatikMan/MLHL-02-EDA-project/blob/main/app/runner.py#L25-L26 - магические константы (если о 31 я догадываюсь, то что такое 8?)
- [x] https://github.com/DramatikMan/MLHL-02-EDA-project/blob/main/app/runner.py#L47 - это имя базы? Если да, то, может быть, его стоит откуда-то считывать, чтобы не напороться на ее изменение в будущем?
- [x] https://github.com/DramatikMan/MLHL-02-EDA-project/blob/main/app/scraper.py#L229 - путь к chromedriver я бы явно не указывал - у меня, допустим, он стоит в `/usr/local/bin`

А так - очень приятный проект с настроенным CI!

Буду ждать обновленную версию!

**Comment by DramatikMan** [comment]
@akhtyamovpavel Внёс исправления.
